///|
pub let lwALT : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt",
)

///|
pub let lwBAG : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag",
)

///|
pub let lwDIR_LANG_STRING : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#dirLangString",
)

///|
pub let lwFIRST : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
)

///|
pub let lwHTML : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML",
)

///|
pub let lwJSON : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#JSON",
)

///|
pub let lwLANG_STRING : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString",
)

///|
pub let lwLIST : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#List",
)

///|
pub let lwNIL : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil",
)

///|
pub let lwOBJECT : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#object",
)

///|
pub let lwPREDICATE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate",
)

///|
pub let lwPROPERTY : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
)

///|
pub let lwREIFIES : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies",
)

///|
pub let lwREST : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
)

///|
pub let lwSEQ : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq",
)

///|
pub let lwSTATEMENT : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement",
)

///|
pub let lwSUBJECT : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject",
)

///|
pub let lwTYPE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
)

///|
pub let lwVALUE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#value",
)

///|
pub let lwXML_LITERAL : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral",
)

///|
pub let lwCLASS : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Class",
)

///|
pub let lwCOMMENT : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#comment",
)

///|
pub let lwCONTAINER : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Container",
)

///|
pub let lwCONTAINER_MEMBERSHIP_PROPERTY : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#ContainerMembershipProperty",
)

///|
pub let lwDATATYPE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Datatype",
)

///|
pub let lwDOMAIN : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#domain",
)

///|
pub let lwIS_DEFINED_BY : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#isDefinedBy",
)

///|
pub let lwLABEL : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#label",
)

///|
pub let lwLITERAL : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Literal",
)

///|
pub let lwMEMBER : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#member",
)

///|
pub let lwRANGE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#range",
)

///|
pub let lwRESOURCE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Resource",
)

///|
pub let lwSEE_ALSO : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#seeAlso",
)

///|
pub let lwSUB_CLASS_OF : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#subClassOf",
)

///|
pub let lwSUB_PROPERTY_OF : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
)

///|
pub let lwANY_URI : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#anyURI",
)

///|
pub let lwBASE_64_BINARY : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#base64Binary",
)

///|
pub let lwBOOLEAN : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#boolean",
)

///|
pub let lwBYTE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#byte",
)

///|
pub let lwDATE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#date",
)

///|
pub let lwDAY_TIME_DURATION : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#dayTimeDuration",
)

///|
pub let lwDATE_TIME : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#dateTime",
)

///|
pub let lwDATE_TIME_STAMP : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#dateTimeStamp",
)

///|
pub let lwDECIMAL : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#decimal",
)

///|
pub let lwDOUBLE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#double",
)

///|
pub let lwDURATION : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#duration",
)

///|
pub let lwFLOAT : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#float",
)

///|
pub let lwG_DAY : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gDay",
)

///|
pub let lwG_MONTH : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gMonth",
)

///|
pub let lwG_MONTH_DAY : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gMonthDay",
)

///|
pub let lwG_YEAR : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gYear",
)

///|
pub let lwG_YEAR_MONTH : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gYearMonth",
)

///|
pub let lwHEX_BINARY : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#hexBinary",
)

///|
pub let lwINT : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#int",
)

///|
pub let lwINTEGER : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#integer",
)

///|
pub let lwLANGUAGE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#language",
)

///|
pub let lwLONG : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#long",
)

///|
pub let lwNAME : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#Name",
)

///|
pub let lwNC_NAME : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#NCName",
)

///|
pub let lwNEGATIVE_INTEGER : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#negativeInteger",
)

///|
pub let lwNMTOKEN : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#NMTOKEN",
)

///|
pub let lwNON_NEGATIVE_INTEGER : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
)

///|
pub let lwNON_POSITIVE_INTEGER : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#nonPositiveInteger",
)

///|
pub let lwNORMALIZED_STRING : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#normalizedString",
)

///|
pub let lwPOSITIVE_INTEGER : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#positiveInteger",
)

///|
pub let lwTIME : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#time",
)

///|
pub let lwSHORT : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#short",
)

///|
pub let lwSTRING : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#string",
)

///|
pub let lwTOKEN : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#token",
)

///|
pub let lwUNSIGNED_BYTE : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedByte",
)

///|
pub let lwUNSIGNED_INT : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedInt",
)

///|
pub let lwUNSIGNED_LONG : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedLong",
)

///|
pub let lwUNSIGNED_SHORT : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedShort",
)

///|
pub let lwYEAR_MONTH_DURATION : NamedNode = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#yearMonthDuration",
)

///|
pub let lwWKT_LITERAL : NamedNode = NamedNode::new_unchecked(
  "http://www.opengis.net/ont/geosparql#wktLiteral",
)
