///|
pub let rdf_alt : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt",
)

///|
pub let rdf_bag : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag",
)

///|
pub let rdf_dir_lang_string : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#dirLangString",
)

///|
pub let rdf_first : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
)

///|
pub let rdf_html : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML",
)

///|
pub let rdf_json : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#JSON",
)

///|
pub let rdf_lang_string : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString",
)

///|
pub let rdf_list : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#List",
)

///|
pub let rdf_nil : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil",
)

///|
pub let rdf_object : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#object",
)

///|
pub let rdf_predicate : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate",
)

///|
pub let rdf_property : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
)

///|
pub let rdf_reifies : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies",
)

///|
pub let rdf_rest : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
)

///|
pub let rdf_seq : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq",
)

///|
pub let rdf_statement : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement",
)

///|
pub let rdf_subject : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject",
)

///|
pub let rdf_type : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
)

///|
pub let rdf_value : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#value",
)

///|
pub let rdf_xml_literal : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral",
)

///|
pub let rdf_class : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Class",
)

///|
pub let rdf_comment : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#comment",
)

///|
pub let rdf_container : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Container",
)

///|
pub let rdf_container_membership_property : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#ContainerMembershipProperty",
)

///|
pub let rdf_datatype : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Datatype",
)

///|
pub let rdf_domain : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#domain",
)

///|
pub let rdf_is_defined_by : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#isDefinedBy",
)

///|
pub let rdf_label : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#label",
)

///|
pub let rdf_literal : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Literal",
)

///|
pub let rdf_member : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#member",
)

///|
pub let rdf_range : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#range",
)

///|
pub let rdf_resource : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Resource",
)

///|
pub let rdf_see_also : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#seeAlso",
)

///|
pub let rdf_sub_class_of : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#subClassOf",
)

///|
pub let rdf_sub_property_of : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
)

///|
pub let rdf_any_uri : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#anyURI",
)

///|
pub let rdf_base_64_binary : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#base64Binary",
)

///|
pub let rdf_boolean : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#boolean",
)

///|
pub let rdf_byte : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#byte",
)

///|
pub let rdf_date : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#date",
)

///|
pub let rdf_day_time_duration : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#dayTimeDuration",
)

///|
pub let rdf_date_time : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#dateTime",
)

///|
pub let rdf_date_time_stamp : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#dateTimeStamp",
)

///|
pub let rdf_decimal : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#decimal",
)

///|
pub let rdf_double : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#double",
)

///|
pub let rdf_duration : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#duration",
)

///|
pub let rdf_float : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#float",
)

///|
pub let rdf_g_day : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gDay",
)

///|
pub let rdf_g_month : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gMonth",
)

///|
pub let rdf_g_month_day : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gMonthDay",
)

///|
pub let rdf_g_year : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gYear",
)

///|
pub let rdf_g_year_month : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gYearMonth",
)

///|
pub let rdf_hex_binary : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#hexBinary",
)

///|
pub let rdf_int : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#int",
)

///|
pub let rdf_integer : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#integer",
)

///|
pub let rdf_language : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#language",
)

///|
pub let rdf_long : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#long",
)

///|
pub let rdf_name : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#Name",
)

///|
pub let rdf_nc_name : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#NCName",
)

///|
pub let rdf_negative_integer : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#negativeInteger",
)

///|
pub let rdf_nmtoken : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#NMTOKEN",
)

///|
pub let rdf_non_negative_integer : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
)

///|
pub let rdf_non_positive_integer : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#nonPositiveInteger",
)

///|
pub let rdf_normalized_string : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#normalizedString",
)

///|
pub let rdf_positive_integer : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#positiveInteger",
)

///|
pub let rdf_time : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#time",
)

///|
pub let rdf_short : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#short",
)

///|
pub let rdf_string : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#string",
)

///|
pub let rdf_token : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#token",
)

///|
pub let rdf_unsigned_byte : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedByte",
)

///|
pub let rdf_unsigned_int : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedInt",
)

///|
pub let rdf_unsigned_long : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedLong",
)

///|
pub let rdf_unsigned_short : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedShort",
)

///|
pub let rdf_year_month_duration : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#yearMonthDuration",
)

///|
pub let rdf_wkt_literal : NamedNodeRef = NamedNode::new_unchecked(
  "http://www.opengis.net/ont/geosparql#wktLiteral",
)
