///|
pub let lwALT : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt",
)

///|
pub let lwBAG : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag",
)

///|
pub let lwDIR_LANG_STRING : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#dirLangString",
)

///|
pub let lwFIRST : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#first",
)

///|
pub let lwHTML : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML",
)

///|
pub let lwJSON : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#JSON",
)

///|
pub let lwLANG_STRING : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString",
)

///|
pub let lwLIST : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#List",
)

///|
pub let lwNIL : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil",
)

///|
pub let lwOBJECT : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#object",
)

///|
pub let lwPREDICATE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate",
)

///|
pub let lwPROPERTY : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
)

///|
pub let lwREIFIES : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies",
)

///|
pub let lwREST : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",
)

///|
pub let lwSEQ : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq",
)

///|
pub let lwSTATEMENT : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement",
)

///|
pub let lwSUBJECT : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject",
)

///|
pub let lwTYPE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
)

///|
pub let lwVALUE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#value",
)

///|
pub let lwXML_LITERAL : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral",
)

///|
pub let lwCLASS : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Class",
)

///|
pub let lwCOMMENT : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#comment",
)

///|
pub let lwCONTAINER : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Container",
)

///|
pub let lwCONTAINER_MEMBERSHIP_PROPERTY : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#ContainerMembershipProperty",
)

///|
pub let lwDATATYPE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Datatype",
)

///|
pub let lwDOMAIN : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#domain",
)

///|
pub let lwIS_DEFINED_BY : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#isDefinedBy",
)

///|
pub let lwLABEL : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#label",
)

///|
pub let lwLITERAL : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Literal",
)

///|
pub let lwMEMBER : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#member",
)

///|
pub let lwRANGE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#range",
)

///|
pub let lwRESOURCE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#Resource",
)

///|
pub let lwSEE_ALSO : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#seeAlso",
)

///|
pub let lwSUB_CLASS_OF : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#subClassOf",
)

///|
pub let lwSUB_PROPERTY_OF : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
)

///|
pub let lwANY_URI : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#anyURI",
)

///|
pub let lwBASE_64_BINARY : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#base64Binary",
)

///|
pub let lwBOOLEAN : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#boolean",
)

///|
pub let lwBYTE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#byte",
)

///|
pub let lwDATE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#date",
)

///|
pub let lwDAY_TIME_DURATION : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#dayTimeDuration",
)

///|
pub let lwDATE_TIME : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#dateTime",
)

///|
pub let lwDATE_TIME_STAMP : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#dateTimeStamp",
)

///|
pub let lwDECIMAL : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#decimal",
)

///|
pub let lwDOUBLE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#double",
)

///|
pub let lwDURATION : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#duration",
)

///|
pub let lwFLOAT : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#float",
)

///|
pub let lwG_DAY : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gDay",
)

///|
pub let lwG_MONTH : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gMonth",
)

///|
pub let lwG_MONTH_DAY : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gMonthDay",
)

///|
pub let lwG_YEAR : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gYear",
)

///|
pub let lwG_YEAR_MONTH : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#gYearMonth",
)

///|
pub let lwHEX_BINARY : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#hexBinary",
)

///|
pub let lwINT : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#int",
)

///|
pub let lwINTEGER : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#integer",
)

///|
pub let lwLANGUAGE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#language",
)

///|
pub let lwLONG : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#long",
)

///|
pub let lwNAME : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#Name",
)

///|
pub let lwNC_NAME : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#NCName",
)

///|
pub let lwNEGATIVE_INTEGER : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#negativeInteger",
)

///|
pub let lwNMTOKEN : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#NMTOKEN",
)

///|
pub let lwNON_NEGATIVE_INTEGER : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
)

///|
pub let lwNON_POSITIVE_INTEGER : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#nonPositiveInteger",
)

///|
pub let lwNORMALIZED_STRING : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#normalizedString",
)

///|
pub let lwPOSITIVE_INTEGER : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#positiveInteger",
)

///|
pub let lwTIME : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#time",
)

///|
pub let lwSHORT : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#short",
)

///|
pub let lwSTRING : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#string",
)

///|
pub let lwTOKEN : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#token",
)

///|
pub let lwUNSIGNED_BYTE : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedByte",
)

///|
pub let lwUNSIGNED_INT : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedInt",
)

///|
pub let lwUNSIGNED_LONG : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedLong",
)

///|
pub let lwUNSIGNED_SHORT : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#unsignedShort",
)

///|
pub let lwYEAR_MONTH_DURATION : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.w3.org/2001/XMLSchema#yearMonthDuration",
)

///|
pub let lwWKT_LITERAL : NamedNodeRef = NamedNodeRef::new_unchecked(
  "http://www.opengis.net/ont/geosparql#wktLiteral",
)
